### ISSUE TITLE
More than one rpm.modulemd_defaults content with the duplicate values for javapackages-tools

### ISSUE THREAD

**Issue by paralllax** [oracle/oracle-linux#84]
Hello,

Currently syncing the public OL8 codeready builder repository runs into some issues. There are duplicate values in the repository metadata for the default javapackages-tools module. This was initially discovered in: https://github.com/pulp/pulp_rpm/issues/2398#issuecomment-1502188478

> Two streams can't be the "default" simultaneously, so one of these two entries should not be here.

I confirmed this configuration is still in place:
```
curl -s "https://yum.oracle.com/repo/OracleLinux/OL8/codeready/builder/x86_64/repodata/1b6d54dbdd3ed3783ac0114387ee77665a679006a828e179132a598173964ac7-modules.yaml.gz" | gunzip | grep -A4 modulemd-defaults | head
document: modulemd-defaults
version: 1
data:
  module: javapackages-tools
  profiles:
--
document: modulemd-defaults
version: 1
data:
  module: javapackages-tools
```

I saw https://bugzilla.oracle.com/bugzilla/ has been retired, I am unsure if this is the correct space to raise the issue. If this needs to be addressed elsewhere, please let me know!
